# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cd6eb8fadab25439690a1b7fdea907f864303433fd39149248deb0d2864b82cbe6b5389ae27553dc36b12e0f9010c5fb0ea8bfd4aa3eda5bf3a1b7486860aaa

test:
  secret_key_base: 2a7a613adabbce2b589dc07656100018fc3fe197712b6229e1d81dfcf66d1f6a1345214b7e1c925645f8b7e66b2f116835e98b5bcbdf5ea22a7f07946f59ef5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
